/*
* This class stores String constants used in application.
*/
public with sharing class ApplicationConstants {
    
    public static String GUIDED_OUTPUT_KNOW = 'Know';
    public static String GUIDED_OUTPUT_SAY  = 'Say';
    public static String GUIDED_OUTPUT_SHOW = 'Show';  
    
    public static String SUCCESS = 'SUCCESS';
    public static String ERROR = 'ERROR';
    public static String NO_ERROR = 'NO_ERROR';
    public static String API_EXCEPTION = 'API_EXCEPTION';
    public static String INVALID_INPUT = 'INVALID_INPUT';       
}